site_name: Kubernetes-Playground
theme: readthedocs

nav:
        - Home: index.md
        - Prepare Host System:
                  - Installation: installation.md
                  - Vagrant: vagrant.md
                  - Kubectl: kubectl-config.md
                  - Documentation: documentation-guide.md
        - k8s-apps:
                  - Nginx: k8s-apps/nginx.md
                  - Jenkins: k8s-apps/jenkins.md
                  - Tekton:
                            - Installation: k8s-apps/tekton/tekton-installation.md
                            - Pipeline: k8s-apps/tekton/tekton-pipeline.md
                  - Flux:
                            - CLI: k8s-apps/fluxv2/fluxv2-cli.md
                            - Installation: k8s-apps/fluxv2/fluxv2-installation.md
        - Analysis: run-container-for-analysis.md
