site_name: Kubernetes-Playground
theme: readthedocs

nav:
    - Home: index.md
    - Installation: installation.md
    - Vagrant: vagrant.md
    - Kubectl: kubectl-config.md
    - Mkdocs: mkdocs-guide.md
    - Operators:
        - Jenkins: operators/jenkins.md