apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: spring-petclinic-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: maven-build
  resources:
  - name: app-git
    resourceSpec:
      type: git
      params:
        - name: url
          value: https://github.com/spring-projects/spring-petclinic.git
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc